DEBUG = true
SECRET_KEY = "change_this_in_prod"
HOST = '0.0.0.0'
PORT= 4000
ENV = "development"


TRUE_CONNECTOR_TEMPLATE = "data/true_connector_resource.json"
TRUE_CONNECTOR_PROXY_URL = "https://localhost:8184/proxy"
TRUE_CONNECTOR_SD_URL = "https://172.17.0.1:8090"
TRUE_CONNECTOR_BROKER_URL = "https://broker-reverseproxy/infrastructure"
TRUE_CONNECTOR_API_USER_NAME = "apiUser"
TRUE_CONNECTOR_API_PASSWORD = "password"


MLFLOW_URI = "http://127.0.0.1:3000"
MLFLOW_ARTIFACT_PATH= "/vagrant/mlflow/mlartifacts"


ORCHESTRATOR_URI = "http://127.0.0.1:4840"

